language: python

install:
  - pip install -r requirements.txt

script:
  - echo "TODO"

deploy:
  provider: cloudfoundry
  username: chris.ko791@gmail.com
  password: 
    secure: LrHTvMZNH65v6lkAzsYcZd4Z/VbG76gRyxMDao/o5QFG38rgnXp/+/xGbrDeQc91Ao/XHPREfnC0NUukGGvdbf+Yzhpb2A2lXcZEVUQTT5d60eGDiETWqh0MVbo9NcN6CFUTCPhvENbz9Ugs1+AS8BtoqXdMbKMTz2aTGK8/mVeeebmJhwB72/UjZKugX0kpm1r9QagV2m1pDjtwcW6xGQZfhdAxBdc73pOam+WwzHXlafEm132aZC722SZU5m34IFWI8vncvrNvStEA6eW9O6V8Im66IwxuG85f6Z7tzF3Y2qJcSMKgwqF1L1ESJXxWvwdB4135KUPwR5XtmHBAWVxVzUpFJ0hlYIbCo+t5rKeIG0ALS2XdFGqjkb00IGSicKvijvO6ApwtHK8AfGTQBHCYmgsKzVF1bHwyjVPjLalqD5QvT5qhbP7pvFmzZAUbI0ALp1W6asnwYhigI6XXPh1qUmy935M80gj4jAc1YLB3168xmYYb+akiGdwdbaooGlGHRqODs7udC3Gkl2uNJKVOVfY4AYA5Uhg6dVE9zBpZjBNjPPmXzLKdbjH0uFbvm55lL9lEDLKd5ewNJlz1OwNbL/BKY7UFJIG8kN+I87qzDS+/waWL/IjvY/idw2HDgav/fmErtujLonBTvCMZCVS/2n8qE3XlXALVB8IJ/FE=
  api: https://api.run.pivotal.io
  organization: pride
  space: development